eye = input("Please enter a character for the eye \n")
print("Beep's  expression is now as follows:      ")
print("##########                                 ")
print("#  {}  {}  #     ".format(eye, eye))
#print("#  " + eye + "  " + eye + "  #"             )
print("#  ----  #                                 ")
print("##########                                 ")                            